### PR TITLE
ch1354: Add optional blacklist file for copy/paste detector

### PR DESCRIPTION
**Pull request by razbakov**
Place `.phpcpdignore` with list of files, which should be ignored
by copy paste detector

If file is empty or doesn't exist it will be ignored

### CODE REVIEW

**Review by Sebastian-bz — APPROVED** [review]

**Comment by sbani** [comment]
You say that you are adding "optional blacklist file" but you always add all changed php files to this file?
Am I right?

**Comment by razbakov** [comment]
@sbani no, why?

**Comment by sbani** [comment]
ok. for me, it looks like that.

**Comment by Sebastian-bz** [comment]
We discussed this topic and for this two files it is ok

**Comment by sbani** [comment]
We are using these things in almost all files. So if you think it's okay for these two files, then you need to do it for all entities

Adding a trait is defenitely the correct way and better way for the future.

**Comment by razbakov** [comment]
@sbani I agree with you

**Pull request merged**
